### ISSUE TITLE
advancenative.com yeni, şu anda yaygın değil ama eksik

### ISSUE THREAD

**Issue by turskishadblock** [bkrcrc/turk-adlist#1]
en başta shiftdelete üzerinde görmüştüm, http://urlquery.net/report.php?id=1490768697348 bu linkte de doğan grubuna ait bir sitede fortiguard'ın yakaladığı gözüküyor. Kendi js dosyaları içine bir çok şeyi gömüyorlar.

**Comment by bkrcrc** [comment]
Maales, yazıda da belirtiğim gibi çoğu reklamı engellemek "host" dosya formatında imkansız. Yalnızca alan adlarını ekleyebiliyorum. Tarayıcılarınıza Adguard Reklam Engelleyici eklentisini kurmanızı tavsiye ederim. Türkçe filtresi vardır.
Teşekkürler,

**Comment by turskishadblock** [comment]
ublock origin ve adguard türkçe filtresi ekli kullanıyorum. Android dns66 denerim de ios için adblock programında liste ekleme yok, orası için tavsiye var mı?

**Comment by bkrcrc** [comment]
Açıkçası IOS kısmı için bu listeyi kullanabileceğiniz bir uygulama var mı bilmiyorum. Ama reklam engellemek için birçok alternatif mevcut.
