### ISSUE TITLE
youtube-nocookie.com

### ISSUE THREAD

**Issue by HellboyPI** [bkrcrc/turk-adlist#2]
Hello!

youtube-nocookie.com is a Google domain and it doesn't serve ads. See [here](http://www.dynamicdrive.com/forums/showthread.php?77919-What-is-https-www-youtube-nocookie-com). This domain should be removed from the blacklist.

**Comment by bkrcrc** [comment]
Thanks, please see the update
https://github.com/bkrcrc/turk-adlist/commit/156cd46af16f6a3bd91544a1fce48e852c6930a3
