### ISSUE TITLE
Yeni Kural Eklemesi

### ISSUE THREAD

**Issue by burak-prd** [bkrcrc/turk-adlist#40]
Merhaba,

Öncelikle bu kullanışlı proje için teşekkür etmek isterim.

Listenizi NextDNS üzerinden kullanıyorum. Girdiğim bazı sitelerde logları incelediğimde aşağıdaki iki kuralla reklam gönderildiğini fark ettim ancak bu kurallar listenizde bulunmuyor.

/reklamlar/*
/reklamlar.

AdGuard Turkish listesi bunu bu şekillerde eklemiş ve tarayıcı eklentisi ile kesebiliyor ancak bu filtre NextDNS üstünden eklenemiyor. O nedenle listeniz bu şekilde reklam olan sayfalarda reklamları engellemiyor. Bu listeyi de geliştirmek adına, bir kullanıcısı olarak eklenmesi konusunda bildirimde bulunmak istiyorum, teşekkürler.

**Comment by bkrucarci** [comment]
Merhaba @burak-prd ,

Liste host tabanlı olduğu için URL bazlı engelleme kuralları eklenemez. Bu tarz isteklerin engellenebilmesi için AdGuard eklentisini tarayıcınıza eklemenizi tavsiye ediyorum. Bahsi geçen kurallar AdGuard Türkçe filtresinde mevcuttur.
AdGuard Türkçe filtresinin geliştirilmesine ben de katkı sağlıyorum.

Reklamsız günler,
Teşekkürler,
